// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW1CGgVQmp_ZIg6J3ZRjZJor1_it1kcCY',
    appId: '1:648840532583:web:cd86c17fcc21ab58f6bac2',
    messagingSenderId: '648840532583',
    projectId: 'fdah-ab1c1',
    authDomain: 'fdah-ab1c1.firebaseapp.com',
    storageBucket: 'fdah-ab1c1.appspot.com',
    measurementId: 'G-DTQ7WQW1V8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB6Z_fzLoTlcUhwPEcoXkRlQcgwx8XWTs',
    appId: '1:648840532583:android:3b9839f6933d21adf6bac2',
    messagingSenderId: '648840532583',
    projectId: 'fdah-ab1c1',
    storageBucket: 'fdah-ab1c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJt31O9jTjboEMQYN-U0aALZ0RgiY8RjQ',
    appId: '1:648840532583:ios:7624cfea2bc4821ef6bac2',
    messagingSenderId: '648840532583',
    projectId: 'fdah-ab1c1',
    storageBucket: 'fdah-ab1c1.appspot.com',
    iosBundleId: 'com.example.fdah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJt31O9jTjboEMQYN-U0aALZ0RgiY8RjQ',
    appId: '1:648840532583:ios:6fd9d6d9730e2e0ff6bac2',
    messagingSenderId: '648840532583',
    projectId: 'fdah-ab1c1',
    storageBucket: 'fdah-ab1c1.appspot.com',
    iosBundleId: 'com.example.fdah.RunnerTests',
  );
}
